# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script: 
            - echo "on branch master"
            - node -v
            - apt-get update
            - apt-get -y install zip
            - npm install
            - npm run build
            - zip -r admin.jarvis.zip dist
            - du -hs admin.jarvis.zip
            - scp admin.jarvis.zip root@3.1.42.42:/mainData/script
            - ssh root@3.1.42.42 'sh /mainData/script/deploy.sh admin.jarvis'  
            - echo Finished uploading
    development:
          - step:
              caches:
                - node
              script: 
                - echo "on branch development"
                - node -v
                - apt-get update
                - apt-get -y install zip
                - npm install
                - npm run build
                - zip -r dist.zip dist
                - du -hs dist.zip
                - scp dist.zip root@103.93.54.165:/mainData/deploy
                - ssh root@103.93.54.165 'sh /mainData/deploy/deploy.sh admin-jarvis'  
                - echo Finished uploading
